# -*- coding: utf-8 -*-
"""cheating_camera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Gihy5zBMLYYsx5yE0oICU6EtBnxiAjJ
"""

!pip uninstall -y tensorflow
!pip install --upgrade protobuf mediapipe

import os

if os.path.exists("mediapipe"):
    os.rename("mediapipe", "mediapipe_local_backup")
    print("Found a local folder named 'mediapipe' and renamed it to fix the conflict!")
if os.path.exists("mediapipe.py"):
    os.rename("mediapipe.py", "mediapipe_local_backup.py")
    print("Found a local file named 'mediapipe.py' and renamed it!")

!pip uninstall -y mediapipe
!pip install mediapipe==0.10.14

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics mediapipe==0.10.21

import torch
from ultralytics import YOLO
import cv2
import zipfile
import mediapipe as mp

mp_face_mesh = mp.solutions.face_mesh

print("All libraries plus MediaPipe are loaded!")

with zipfile.ZipFile("/content/drive/MyDrive/senior_project/head_movement_dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/head_dataset")

with zipfile.ZipFile("/content/drive/MyDrive/senior_project/phone_detection_dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/phone_dataset")

print("Datasets extracted")

device = 0 if torch.cuda.is_available() else "cpu"
print(device)

#head_model = YOLO("yolov8n.pt")

#head_model.train(
 #   data="/content/head_dataset/data.yaml",
  #  epochs=30,
   # imgsz=640,
    #batch=8,
    #device=device,
    #project="/content/drive/MyDrive/senior_project",
    #name="head_model_3"
#)

#phone_model = YOLO("yolov8n.pt")

#phone_model.train(
 #   data="/content/phone_dataset/data.yaml",
  #  epochs=30,
   # imgsz=640,
    #batch=8,
    #device=device,
    #project="/content/drive/MyDrive/senior_project",
    #name="phone_model_2"
#)

#phone_model = YOLO("/content/drive/MyDrive/senior_project/phone_model_2/weights/last.pt")
#phone_model.train(resume=True)


import torch
from ultralytics import YOLO

_original_load = torch.load
torch.load = lambda *args, **kwargs: _original_load(*args, **{**kwargs, 'weights_only': False})

# 1. load the phone model
phone_model = YOLO("/content/drive/MyDrive/senior_project/phone_model_2/weights/last.pt")

# 2. run the validation to generate the metrics
metrics = phone_model.val(
    data="/content/phone_dataset/data.yaml",
    imgsz=640
)

# 3. calculate and print the results
precision = metrics.box.mp
recall = metrics.box.mr
accuracy = (2 * precision * recall) / (precision + recall + 1e-6)

print("mAP50-95:", metrics.box.map)
print("mAP50:", metrics.box.map50)
print("Precision:", precision)
print("Recall:", recall)
print("Accuracy:", accuracy)

from ultralytics import YOLO

#head_model = YOLO("/content/drive/MyDrive/senior_project/head_model_3/weights/best.pt")
phone_model = YOLO("/content/drive/MyDrive/senior_project/phone_model_2/weights/best.pt")
person_counter = YOLO('yolov8n.pt')

print("Models loaded")

'''
import cv2
import numpy as np
import traceback
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode, b64encode
from ultralytics import YOLO

#CHEATING LOGIC
def apply_yolo_cheating_logic(img, consecutive_cheating_frames):
    phone_detected_alarm = False
    is_looking_away = False

    phone_results = phone_model(img, verbose=False)
    head_results = head_model(img, verbose=False, agnostic_nms=True)

#phone detection:
    for r in phone_results:
        for box in r.boxes:
            conf = float(box.conf[0])
            if conf >= 0.40:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                phone_detected_alarm = True
                cv2.rectangle(img, (x1, y1), (x2, y2), (0, 0, 255), 2)
                cv2.putText(img, f"Phone! {conf:.2f}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

#head detection:
    valid_heads_for_cheating =[]
    total_people_in_frame = 0

    for r in head_results:
        for box in r.boxes:
            conf = float(box.conf[0])
            if conf >= 0.35:
                total_people_in_frame += 1

            # Must still be > 50% confident to actually judge if it's 'cheating' or 'normal'
            if conf >= 0.50:
                valid_heads_for_cheating.append(box)

    for box in valid_heads_for_cheating:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        cls_id = int(box.cls[0])
        conf = float(box.conf[0])
        class_name = head_model.names[cls_id].lower()

        if class_name == 'cheating':
            if total_people_in_frame >= 2:
                is_looking_away = True
                cv2.rectangle(img, (x1, y1), (x2, y2), (0, 165, 255), 2) # Orange Box
                cv2.putText(img, f"Looking at someone! {conf:.2f}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 165, 255), 2)
            else:
                # Alone
                cv2.rectangle(img, (x1, y1), (x2, y2), (255, 255, 0), 2) # Cyan Box
                cv2.putText(img, f"Looking away (Alone) {conf:.2f}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 0), 2)
        else:
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)   # Green Box
            cv2.putText(img, f"Normal {conf:.2f}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    #timer:
    if is_looking_away:
        consecutive_cheating_frames += 1
    else:
        consecutive_cheating_frames = max(0, consecutive_cheating_frames - 2)

    #DEBUGGING:
    cv2.putText(img, f"People in Frame: {total_people_in_frame}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)
    cv2.putText(img, f"Cheating Timer: {consecutive_cheating_frames}/8", (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)

    # cheating detected:
    cheating_alarm_active = False

    if phone_detected_alarm or consecutive_cheating_frames >= 8:
        cheating_alarm_active = True

    if cheating_alarm_active:
        cv2.putText(img, "WARNING: CHEATING DETECTED!", (20, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 3)
        cv2.rectangle(img, (0,0), (img.shape[1], img.shape[0]), (0, 0, 255), 10)

    return img, consecutive_cheating_frames

# COLAB JAVASCRIPT WEBCAM:
def js_to_image(js_reply):
    image_bytes = b64decode(js_reply.split(',')[1])
    jpg_as_np = np.frombuffer(image_bytes, dtype=np.uint8)
    img = cv2.imdecode(jpg_as_np, flags=1)
    return img

def bbox_to_bytes(bbox_array):
    _, bbox_buffer = cv2.imencode('.jpg', bbox_array)
    bbox_bytes = b64encode(bbox_buffer).decode('utf-8')
    return bbox_bytes

def video_stream():
  js = Javascript('''
    var video; var div = null; var stream; var captureCanvas; var imgElement; var labelElement;
    var pendingResolve = null; var shutdown = false;
    function removeDom() {
       if(stream){stream.getVideoTracks()[0].stop();}
       if(video){video.remove();}
       if(div){div.remove();}
       video = null; div = null; stream = null; imgElement = null; captureCanvas = null; labelElement = null;
    }
    function onAnimationFrame() {
      if (!shutdown) { window.requestAnimationFrame(onAnimationFrame); }
      if (pendingResolve) {
        var result = "";
        if (!shutdown) {
          captureCanvas.getContext('2d').drawImage(video, 0, 0, 640, 480);
          result = captureCanvas.toDataURL('image/jpeg', 0.8)
        }
        var lp = pendingResolve; pendingResolve = null; lp(result);
      }
    }
    async function createDom() {
      if (div !== null) { return stream; }
      div = document.createElement('div');
      div.style.border = '2px solid black'; div.style.padding = '3px'; div.style.width = '100%'; div.style.maxWidth = '600px';
      document.body.appendChild(div);
      const modelOut = document.createElement('div');
      modelOut.innerHTML = "<span>Status: WebCam Running (Click video to stop)</span>";
      labelElement = document.createElement('span'); div.appendChild(modelOut);
      video = document.createElement('video'); video.style.display = 'block'; video.width = div.clientWidth - 6;
      video.setAttribute('playsinline', ''); video.onclick = () => { shutdown = true; };
      stream = await navigator.mediaDevices.getUserMedia({video: { facingMode: "user"}});
      div.appendChild(video);
      imgElement = document.createElement('img'); imgElement.style.position = 'absolute'; imgElement.style.zIndex = 1;
      imgElement.onclick = () => { shutdown = true; }; div.appendChild(imgElement);
      video.srcObject = stream; await video.play();
      captureCanvas = document.createElement('canvas'); captureCanvas.width = 640; captureCanvas.height = 480;
      window.requestAnimationFrame(onAnimationFrame); return stream;
    }
    async function stream_frame(label, imgData) {
      if (shutdown) { removeDom(); shutdown = false; return ''; }
      var preCreate = Date.now(); stream = await createDom();
      if (imgData != "") {
        var videoRect = video.getClientRects()[0];
        imgElement.style.top = videoRect.top + "px"; imgElement.style.left = videoRect.left + "px";
        imgElement.style.width = videoRect.width + "px"; imgElement.style.height = videoRect.height + "px";
        imgElement.src = imgData;
      }
      var result = await new Promise(function(resolve, reject) { pendingResolve = resolve; });
      shutdown = false; return {'img': result};
    }
    ''')
  display(js)

def video_frame(label, bbox):
  data = eval_js('stream_frame("{}", "{}")'.format(label, bbox))
  return data

# LIVE DETECTION:
print("Starting webcam... Please allow camera access in your browser.")
video_stream()
label_html = 'Running Cheating Detection...'
bbox = ''

consecutive_cheating_frames = 0

while True:
    try:
        js_reply = video_frame(label_html, bbox)

        if not js_reply or not js_reply.get("img"):
            print("Video stopped by user.")
            break

        img = js_to_image(js_reply["img"])
        processed_img, consecutive_cheating_frames = apply_yolo_cheating_logic(img, consecutive_cheating_frames)
        bbox = "data:image/jpeg;base64," + bbox_to_bytes(processed_img)

    except Exception as e:
        print("\n❌ CRASH DETECTED!")
        print(f"Error message: {e}")
        traceback.print_exc()
        print("Stopping stream...")
        break

print("Webcam successfully closed.")
'''

print("1. Deleting folders")
!pip uninstall -y mediapipe protobuf ultralytics
!rm -rf /usr/local/lib/python3.12/dist-packages/mediapipe*
!rm -rf /usr/local/lib/python3.12/dist-packages/google/protobuf*

print("2. Installing the versions")
!pip install --no-cache-dir mediapipe==0.10.13 ultralytics==8.2.0 protobuf==4.25.3

print("3. Setting the environment...")
import os
import sys

# Force restart so error is cleared from memory
os.kill(os.getpid(), 9)

print("4. Loading the project...")

import torch
import mediapipe as mp
from ultralytics import YOLO

_original_load = torch.load
torch.load = lambda *args, **kwargs: _original_load(*args, **{**kwargs, 'weights_only': False})

# Load Phone Model
phone_model = YOLO("/content/drive/MyDrive/senior_project/phone_model_2/weights/last.pt")

# Load Person Counter
person_counter = YOLO('yolov8n.pt')

# Initialize MediaPipe Face Tracking:
mp_face_mesh = mp.solutions.face_mesh
face_mesh = mp_face_mesh.FaceMesh(
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5,
    max_num_faces=5
)

print("The models and MediaPipe are fully loaded and ready!")

# Force install everything and ignore the internal conflicts
#!pip install --no-deps mediapipe==0.10.21
#!pip install protobuf==5.26.1

# Restart the session to apply changes
#import os
#os.kill(os.getpid(), 9)

#import mediapipe as mp
#from ultralytics import YOLO

# Load Phone Model
#phone_model = YOLO("/content/drive/MyDrive/senior_project/phone_model_2/weights/last.pt")

# Load Person Counter
#person_counter = YOLO('yolov8n.pt')

# Initialize MediaPipe Face Tracking:
#mp_face_mesh = mp.solutions.face_mesh
#face_mesh = mp_face_mesh.FaceMesh(
 #   min_detection_confidence=0.5,
  #  min_tracking_confidence=0.5,
   # max_num_faces=5
#)

#print("Models and MediaPipe successfully loaded!")

import cv2
import numpy as np
import traceback
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode, b64encode

# CHEATING LOGIC (YOLO + MediaPipe):
# cheating logic code:
def apply_hybrid_cheating_logic(img, consecutive_cheating_frames):
    phone_detected_alarm = False
    is_looking_away = False

    img_h, img_w, _ = img.shape

    # DETECT PHONE (YOLO):
    phone_results = phone_model(img, verbose=False)
    for r in phone_results:
        for box in r.boxes:
            conf = float(box.conf[0])
            if conf >= 0.40:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                phone_detected_alarm = True
                cv2.rectangle(img, (x1, y1), (x2, y2), (0, 0, 255), 2)
                cv2.putText(img, f"Phone! {conf:.2f}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

    # FIND WHERE PEOPLE ARE SITTING (YOLO):
    person_centers = []
    person_results = person_counter(img, classes=[0], verbose=False)

    for r in person_results:
        for box in r.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            # Find the center X coordinate of this person's body:
            center_x = (x1 + x2) // 2
            person_centers.append(center_x)

    total_people_in_frame = len(person_centers)

    # PROCESS HEAD (MediaPipe):
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    face_results = face_mesh.process(img_rgb)

    if face_results.multi_face_landmarks:
        for face_landmarks in face_results.multi_face_landmarks:
            face_2d = []
            face_3d =[]

            for idx, lm in enumerate(face_landmarks.landmark):
                if idx in[33, 263, 1, 61, 291, 199]:
                    if idx == 1: # Nose tip
                        nose_2d = (int(lm.x * img_w), int(lm.y * img_h))
                    x, y = int(lm.x * img_w), int(lm.y * img_h)
                    face_2d.append([x, y])
                    face_3d.append([x, y, lm.z])

            face_2d = np.array(face_2d, dtype=np.float64)
            face_3d = np.array(face_3d, dtype=np.float64)

            focal_length = 1 * img_w
            cam_matrix = np.array([[focal_length, 0, img_h / 2],[0, focal_length, img_w / 2], [0, 0, 1]])
            dist_matrix = np.zeros((4, 1), dtype=np.float64)

            success, rot_vec, trans_vec = cv2.solvePnP(face_3d, face_2d, cam_matrix, dist_matrix)
            rmat, jac = cv2.Rodrigues(rot_vec)
            angles, mtxR, mtxQ, Qx, Qy, Qz = cv2.RQDecomp3x3(rmat)

            # Get Angles:
            y_angle = angles[1] * 360  # Yaw (Left/Right)
            x_angle = angles[0] * 360  # Pitch (Up/Down)

            nose_x = nose_2d[0]

            # CHECK SURROUNDINGS: Are there bodies to the left or right of THIS face?
            # We use 100 pixels as a buffer so it doesn't accidentally count the person's own body
            people_to_the_left = sum(1 for px in person_centers if px < nose_x - 100)
            people_to_the_right = sum(1 for px in person_centers if px > nose_x + 100)

            # Determine direction of head turn:
            looking_screen_left = y_angle < -15
            looking_screen_right = y_angle > 15
            looking_down = x_angle < -15

            is_cheating_turn = False
            status_text = "Forward"
            dot_color = (0, 255, 0) # Green

            # SPATIAL AWARENESS LOGIC:
            if looking_screen_left:
                if people_to_the_left > 0:
                    is_cheating_turn = True
                    status_text = "Looking at friend (Left)!"
                    dot_color = (0, 165, 255) # Orange
                else:
                    status_text = "Looking away (Safe)"
                    dot_color = (255, 255, 0) # Cyan

            elif looking_screen_right:
                if people_to_the_right > 0:
                    is_cheating_turn = True
                    status_text = "Looking at friend (Right)!"
                    dot_color = (0, 165, 255)
                else:
                    status_text = "Looking away (Safe)"
                    dot_color = (255, 255, 0)

            elif looking_down:
                status_text = "Looking down (Safe)"
                dot_color = (255, 255, 0)

            # Apply text based on status:
            if is_cheating_turn:
                is_looking_away = True

            cv2.putText(img, status_text, (nose_x-50, nose_2d[1]-20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, dot_color, 2)
            cv2.circle(img, nose_2d, 5, dot_color, -1)

    # TIMER:
    if is_looking_away:
        consecutive_cheating_frames += 1
    else:
        consecutive_cheating_frames = max(0, consecutive_cheating_frames - 2)

    # DEBUGGING & ALARMS
    cv2.putText(img, f"People in Frame: {total_people_in_frame}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)
    cv2.putText(img, f"Cheating Timer: {consecutive_cheating_frames}/8", (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)

    cheating_alarm_active = False
    if phone_detected_alarm or consecutive_cheating_frames >= 8:
        cheating_alarm_active = True

    if cheating_alarm_active:
        cv2.putText(img, "WARNING: CHEATING DETECTED!", (20, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 3)
        cv2.rectangle(img, (0,0), (img.shape[1], img.shape[0]), (0, 0, 255), 10)

    return img, consecutive_cheating_frames

consecutive_cheating_frames = 0

!pip install flask flask-socketio pyngrok ultralytics mediapipe==0.10.21 flask-cors eventlet

#!pip install flask-socketio pyngrok ultralytics mediapipe "werkzeug<3.0.0"
!pip uninstall -y gevent gevent-websocket flask-socketio werkzeug flask
!pip install Flask==2.2.5 Werkzeug==2.2.3 Flask-SocketIO==5.3.6 simple-websocket==0.10.1 mysql-connector-python pyngrok flask-cors ultralytics mediapipe opencv-python-headless

#!pip uninstall -y gevent gevent-websocket flask-socketio werkzeug flask
#!pip install Flask==2.2.5 Werkzeug==2.2.3 Flask-SocketIO==5.3.6 simple-websocket==0.10.1 mysql-connector-python pyngrok flask-cors ultralytics mediapipe opencv-python-headless

import cv2
import numpy as np
import base64
import mysql.connector
import torch
from flask import Flask, request, jsonify
from flask_socketio import SocketIO, emit
from flask_cors import CORS
from pyngrok import ngrok
from ultralytics import YOLO
import mediapipe as mp
from werkzeug.security import generate_password_hash, check_password_hash

if not hasattr(torch, '_safely_patched'):
    _original_load = torch.load
    torch.load = lambda *args, **kwargs: _original_load(*args, **{**kwargs, 'weights_only': False})
    torch._safely_patched = True

app = Flask(__name__)
CORS(app)

socketio = SocketIO(app, cors_allowed_origins="*", async_mode='threading')

# AIVEN MYSQL CREDENTIALS (SECRET INFO)
DB_CONFIG = {
    #"host": "",
    #"port": ,
    #"user": "",
    #"password": "",
    #"database": "proctor_ai"
}

def get_db_connection():
    return mysql.connector.connect(**DB_CONFIG)

# AI MODELS
phone_model = YOLO("/content/drive/MyDrive/senior_project/phone_model_2/weights/last.pt")
person_counter = YOLO('yolov8n.pt')
mp_face_mesh = mp.solutions.face_mesh
face_mesh = mp_face_mesh.FaceMesh(min_detection_confidence=0.5, min_tracking_confidence=0.5, max_num_faces=5)

student_tracker = {}
INTERNAL_ID_COUNTER = 1
is_processing = False

@app.route('/api/register', methods=['POST'])
def register():
    data = request.json
    try:
        hashed_pw = generate_password_hash(data['pass'], method='pbkdf2:sha256')
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute(
            "INSERT INTO users (title, first_name, last_name, email, password) VALUES (%s, %s, %s, %s, %s)",
            (data['title'], data['firstName'], data['lastName'], data['email'], hashed_pw)
        )
        conn.commit()
        cursor.close()
        conn.close()
        return jsonify({"success": True, "message": "User registered successfully!"})
    except mysql.connector.IntegrityError:
        return jsonify({"success": False, "message": "Email already exists!"}), 400
    except Exception as e:
        return jsonify({"success": False, "message": str(e)}), 500

@app.route('/api/login', methods=['POST'])
def login():
    data = request.json
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT title, first_name, last_name, password FROM users WHERE email = %s", (data['email'],))
    user = cursor.fetchone()
    cursor.close()
    conn.close()

    if user and check_password_hash(user['password'], data['pass']):
        full_name = f"{user['title']} {user['first_name']} {user['last_name']}"
        return jsonify({"success": True, "name": full_name})
    return jsonify({"success": False, "message": "Invalid email or password."}), 401

@app.route('/api/save_alert', methods=['POST'])
def save_alert():
    data = request.json
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute('''
            INSERT INTO alerts (id, exam_name, student_name, type, severity, confidence, time, date, detail, snapshot, resolution, proctor_name)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ''', (
            data['id'], data['exam_name'], data['student_name'], data['type'],
            data['severity'], data['confidence'], data['time'], data['date'],
            data['detail'], data['snapshot'], data['resolution'], data['proctor_name']
        ))
        conn.commit()
        return jsonify({"success": True})
    except Exception as e:
        print("SQL Save Error:", e)
        return jsonify({"success": False, "error": str(e)})
    finally:
        cursor.close()
        conn.close()

@app.route('/api/get_alerts', methods=['GET'])
def get_alerts():
    proctor = request.args.get('proctor')
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    try:
        cursor.execute("SELECT * FROM alerts WHERE proctor_name = %s ORDER BY id DESC", (proctor,))
        alerts = cursor.fetchall()
        return jsonify({"success": True, "alerts": alerts})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})
    finally:
        cursor.close()
        conn.close()

@app.route('/api/update_alert', methods=['POST'])
def update_alert():
    data = request.json
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("UPDATE alerts SET resolution = %s WHERE id = %s", (data['resolution'], data['id']))
        conn.commit()
        return jsonify({"success": True})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})
    finally:
        cursor.close()
        conn.close()

@app.route('/api/delete_alert', methods=['POST'])
def delete_alert():
    data = request.json
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM alerts WHERE id = %s", (data['id'],))
        conn.commit()
        return jsonify({"success": True})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})
    finally:
        cursor.close()
        conn.close()

def process_frame(img):
    global student_tracker, INTERNAL_ID_COUNTER
    img_h, img_w, _ = img.shape
    person_results = person_counter(img, classes=[0], conf=0.40, verbose=False)
    current_frame_detections = []

    for r in person_results:
        for box in r.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            if (x2 - x1) < 80 or (y2 - y1) < 80: continue
            current_frame_detections.append({'bbox': [x1, y1, x2, y2], 'cx': (x1+x2)//2, 'cy': (y1+y2)//2})

    for tid in list(student_tracker.keys()):
        student_tracker[tid]['missed_frames'] += 1
        if student_tracker[tid]['missed_frames'] > 30: del student_tracker[tid]

    matched_tids = []
    for det in current_frame_detections:
        matched_id = None
        min_dist = 150
        for tid, tdata in student_tracker.items():
            if tid in matched_tids: continue
            if np.sqrt((det['cx'] - tdata['last_cx'])**2 + (det['cy'] - tdata['last_cy'])**2) < min_dist:
                min_dist = np.sqrt((det['cx'] - tdata['last_cx'])**2 + (det['cy'] - tdata['last_cy'])**2)
                matched_id = tid

        if matched_id is None:
            matched_id = INTERNAL_ID_COUNTER
            INTERNAL_ID_COUNTER += 1
            student_tracker[matched_id] = {'timer': 0, 'alert_locked': False}

        student_tracker[matched_id].update({'last_cx': det['cx'], 'last_cy': det['cy'], 'bbox': det['bbox'], 'missed_frames': 0})
        matched_tids.append(matched_id)

    active_students = [tid for tid, tdata in student_tracker.items() if tdata['missed_frames'] == 0]
    active_students.sort(key=lambda tid: student_tracker[tid]['last_cx'])
    all_active_centers = [student_tracker[tid]['last_cx'] for tid in active_students]
    processed_students = []

    for display_index, tid in enumerate(active_students):
        tdata = student_tracker[tid]
        display_name = f"Student {display_index + 1}"
        x1, y1, x2, y2 = tdata['bbox']

        pad_x, pad_y, pad_top = int((x2 - x1) * 0.20), int((y2 - y1) * 0.15), int((y2 - y1) * 0.30)
        crop_x1, crop_y1 = max(0, x1 - pad_x), max(0, y1 - pad_top)
        crop_x2, crop_y2 = min(img_w, x2 + pad_x), min(img_h, y2 + pad_y)
        crop = img[crop_y1:crop_y2, crop_x1:crop_x2]

        if crop.size == 0: continue
        crop_h, crop_w, _ = crop.shape

        phone_results = phone_model(crop, verbose=False)
        max_phone_conf = max([float(b.conf[0]) for r in phone_results for b in r.boxes], default=0.0)
        has_phone = max_phone_conf >= 0.80

        is_looking = False
        face_res = face_mesh.process(cv2.cvtColor(crop, cv2.COLOR_BGR2RGB))

        if face_res.multi_face_landmarks:
            face_2d, face_3d = [], []
            for idx, lm in enumerate(face_res.multi_face_landmarks[0].landmark):
                if idx in [33, 263, 1, 61, 291, 199]:
                    face_2d.append([int(lm.x * crop_w), int(lm.y * crop_h)])
                    face_3d.append([int(lm.x * crop_w), int(lm.y * crop_h), lm.z])

            if len(face_2d) == 6:
                success, rot_vec, trans_vec = cv2.solvePnP(np.array(face_3d, dtype=np.float64), np.array(face_2d, dtype=np.float64), np.array([[1*crop_w, 0, crop_h/2], [0, 1*crop_w, crop_w/2], [0, 0, 1]]), np.zeros((4, 1), dtype=np.float64))
                y_angle = cv2.RQDecomp3x3(cv2.Rodrigues(rot_vec)[0])[0][1] * 360

                left_neighbors = sum(1 for cx in all_active_centers if cx < tdata['last_cx'] - 100)
                right_neighbors = sum(1 for cx in all_active_centers if cx > tdata['last_cx'] + 100)
                if (y_angle < -15 and left_neighbors > 0) or (y_angle > 15 and right_neighbors > 0):
                    is_looking = True

        timer, locked = tdata['timer'], tdata['alert_locked']
        timer = timer + 1 if is_looking else max(0, timer - 1)
        if timer == 0 and not has_phone: locked = False

        should_alert, status, color = False, "Safe", "#10b981"
        conf_score = 0

        if has_phone:
            if not locked: should_alert, locked = True, True
            conf_score, status, color = int(max_phone_conf * 100), "Phone Usage", "#ef4444"
        else:
            if timer >= 8:
                if not locked: should_alert, locked = True, True
                conf_score, status, color = min(99, 70 + (timer * 2)), "Cheating (Looking at Friend)", "#ef4444"
            elif timer > 0: status, color = "Looking at Friend...", "#f59e0b"

        _, buf = cv2.imencode('.jpg', crop)
        student_tracker[tid]['timer'], student_tracker[tid]['alert_locked'] = timer, locked
        processed_students.append({"id": display_name, "label": display_name, "status": status, "color": color, "is_cheating": should_alert, "real_conf": conf_score, "timer": timer, "image": f"data:image/jpeg;base64,{base64.b64encode(buf).decode('utf-8')}"})

    return processed_students

@socketio.on('process_frame')
def handle_frame(data):
    global is_processing
    if is_processing: return
    try:
        is_processing = True
        encoded_data = data['image'].split(',')[1]
        img = cv2.imdecode(np.frombuffer(base64.b64decode(encoded_data), np.uint8), cv2.IMREAD_COLOR)
        if img is not None:
            results = process_frame(img)
            emit('processed_data', results)
    except Exception as e:
        print(f"Error handling frame: {e}")
    finally:
        is_processing = False

if __name__ == '__main__':
    ngrok.kill()
    # SECRET TOCKEN HERE -> ngrok.set_auth_token("")
    print(f"\n\n {ngrok.connect(5000).public_url} \n\n")
    socketio.run(app, host='0.0.0.0', port=5000, allow_unsafe_werkzeug=True)